### ISSUE TITLE
enabling again

### ISSUE THREAD

**Issue by randy-johnson** [Prospress/action-scheduler-disable-default-runner#2]
It wasn't clear in the readme if disabling this plugin will active the subscriptions again?\

I am guessing it does but want to be sure before giving it a try.

**Comment by rrennick** [comment]
> It wasn't clear in the readme if disabling this plugin will active the subscriptions again?\

This plugin disables the default queue runners. If you deactivate this then the queue runners will start processing `Pending` actions. You need to look at your pending action list to see what have a scheduled date in the past. The default ordering in the list table is the order they would be processed in.
