### ISSUE TITLE
Do subscriptions process again after enabling

### ISSUE THREAD

**Issue by randy-johnson** [Prospress/action-scheduler-disable-default-runner#3]
If I install this plugin on Friday and enable again on Monday do the subscriptions that should have processed Saturday and Sunday run on Monday?

**Comment by rrennick** [comment]
@randy-johnson Yes, you can use this plugin to temporarily suspend processing actions. As an addition to my comment on #2, you can view your pending actions under Tools -> Scheduled Actions -> Pending.
